/* Generated from cabal_msg.xml skillNNNN entries. Do not edit. */
#include "skill_names.h"

#include <stddef.h>
#include <stdint.h>

typedef struct {
    uint16_t id;
    const char *name;
} PwSkillName;

static const PwSkillName k_names[] = {
    {1, "Flash Draw"},
    {2, "Impact Stab"},
    {3, "Power Stab"},
    {4, "Stab Slash"},
    {5, "Force Stab"},
    {6, "Raging Thrust"},
    {7, "Death Cross"},
    {8, "Wild Strike"},
    {9, "Illusion Stab"},
    {10, "Heavy Slash"},
    {11, "Power Slash"},
    {12, "Press Impact"},
    {13, "Slash Break"},
    {14, "Rolling Crash"},
    {15, "Guillotine"},
    {16, "Double Slash"},
    {17, "Force Slash"},
    {18, "Triple Slash"},
    {19, "Force Break"},
    {20, "Hasing Dance"},
    {21, "Force Drive"},
    {22, "Rising Shot"},
    {23, "Rising Blade"},
    {24, "Double Rising"},
    {25, "Soaring Shot"},
    {26, "Cascade Break"},
    {27, "Storm Grind"},
    {28, "Earth Divide"},
    {29, "Dance of Ruin"},
    {30, "Charge"},
    {31, "Assault"},
    {32, "Shield Charge"},
    {33, "Force Assault"},
    {34, "Whirlwind"},
    {35, "Blade Scud"},
    {36, "Shield Break"},
    {37, "Infernal Impact"},
    {38, "Round Cut"},
    {39, "Spiral Doom"},
    {40, "Mirage Grind"},
    {41, "Storm Crush"},
    {42, "Infernal Stigma"},
    {43, "Sword Cannon"},
    {44, "Twin-moon Slash"},
    {45, "Shield Ray"},
    {46, "Abyssal Crystal"},
    {47, "Sword Cannon II"},
    {48, "Twin-moon Slash II"},
    {49, "Shield Ray II"},
    {50, "Abyssal Crystal II"},
    {51, "Terra Break"},
    {52, "Blade Cry"},
    {53, "Shield Explosion"},
    {54, "Force Impact"},
    {55, "Seismic Wave"},
    {56, "Lightning Slash"},
    {57, "Shield Splinter"},
    {58, "Assassinate"},
    {59, "Restraint2WA"},
    {60, "Restraint2BL"},
    {61, "Restraint2FS"},
    {62, "Restraint2FB"},
    {63, "Sword Quake"},
    {64, "Death Tempest"},
    {65, "Shield Grenade"},
    {66, "Seal of Damnation"},
    {67, "Bow Slash"},
    {68, "Force Kick"},
    {69, "Throw Knife"},
    {70, "Vital Interfere"},
    {71, "Provocation"},
    {72, "Apocalypse Decision"},
    {73, "Infinity Blaze"},
    {74, "Hell Crasher"},
    {75, "Quake Cataclysm"},
    {76, "Crescent Slash"},
    {77, "Heavy Crush"},
    {78, "Waving Slash"},
    {79, "Reverse Step"},
    {80, "Moonlight Smash"},
    {81, "Moon Rising"},
    {82, "Cross on Earth"},
    {83, "Storm Slash"},
    {84, "Shadow Step"},
    {85, "Rapid Dash"},
    {86, "Moon Strike"},
    {87, "Fadeaway"},
    {88, "Mystic Dash"},
    {89, "Eternal Slash"},
    {90, "Trinity Slash"},
    {91, "Rising Storm"},
    {92, "Chakram Break"},
    {93, "Blade of Fury"},
    {94, "Chakram Tornado"},
    {95, "Freezing Strike"},
    {96, "Momentary Illumination"},
    {97, "Crimson Blade"},
    {98, "Illusion Blade"},
    {99, "Lightning Revenge"},
    {100, "Magic Arrow"},
    {101, "Terra Arrow"},
    {102, "Aqua Arrow"},
    {103, "Wind Arrow"},
    {104, "Fire Arrow"},
    {105, "Freezing Arrow"},
    {106, "Lightning Arrow"},
    {107, "Magic Blast"},
    {108, "Stone Blast"},
    {109, "Aqua Blast"},
    {110, "Wind Blast"},
    {111, "Fire Blast"},
    {112, "Ice Blast"},
    {113, "Lightning Blast"},
    {114, "Magic Lance"},
    {115, "Terra Lance"},
    {116, "Aqua Lance"},
    {117, "Wind Lance"},
    {118, "Fire Lance"},
    {119, "Freezing Lance"},
    {120, "Lightning Lance"},
    {121, "Magic Cannon"},
    {122, "Stone Cannon"},
    {123, "Aqua Cannon"},
    {124, "Wind Cannon"},
    {125, "Fire Cannon"},
    {126, "Crystal Cannon"},
    {127, "Lightning Cannon"},
    {128, "Burning Hand"},
    {129, "Freeze"},
    {130, "Dig Bomb"},
    {131, "Icicle Shower"},
    {132, "Wind Cutter"},
    {133, "Hydro Disk"},
    {134, "Lightning Strike"},
    {135, "Acid Trap"},
    {136, "Vacuum"},
    {137, "Chain Explosion"},
    {138, "Hail Storm"},
    {139, "Extreme Dual Cannon"},
    {140, "Arctic Field"},
    {141, "Space Collapse"},
    {142, "Restraint1WI"},
    {143, "Restraint2WI"},
    {144, "Immortality(QA)"},
    {145, "Sureside(QA)"},
    {146, "Power Word Kill(QA)"},
    {147, "Pury of Heaven(QA)"},
    {148, "Power Shot"},
    {149, "Critical Shot"},
    {150, "Explosion Shot"},
    {151, "Poison Arrow"},
    {152, "Shadow Shot"},
    {153, "Drilled Shot"},
    {154, "Prismatic Arrow"},
    {155, "Gravity Distortion"},
    {156, "Shooting Star"},
    {157, "Shield Shock"},
    {158, "Flying Shield"},
    {159, "Blade of Judgement"},
    {160, "Restraint1FA"},
    {161, "Restraint2FA"},
    {162, "FB Magic 5"},
    {163, "FB Magic 7"},
    {164, "FB Magic 9"},
    {165, "FS Magic 7"},
    {166, "FS Magic 9"},
    {167, "Meteorite"},
    {168, "Sonic Shooter"},
    {169, "Glacial Trap"},
    {170, "Arrow Barrage"},
    {171, "Genocider"},
    {172, "Genocider Attack A"},
    {173, "Genocider Attack B"},
    {174, "Genocider Specialty Stage 1"},
    {175, "Genocider Specialty Stage 2"},
    {176, "Genocider Specialty Stage 3"},
    {177, "Rage"},
    {178, "Bloodyrusk"},
    {179, "Vital Charge"},
    {180, "Art of Rage"},
    {181, "Sight Increase"},
    {182, "Rage Resist"},
    {183, "Battle Fury"},
    {184, "Aegis"},
    {185, "Mortal Combat"},
    {186, "Rage Shield"},
    {187, "Hyper Odd Circle"},
    {188, "Dread"},
    {189, "Overwhelming"},
    {190, "Hawk Hunter"},
    {191, "Shield Taunt"},
    {192, "Chakram Slam"},
    {193, "Multiple Canon"},
    {194, "Arrow Forest"},
    {195, "Piercing Shield"},
    {196, "Adrenaline of Rage"},
    {200, "Blade Force"},
    {201, "Blade Aura"},
    {202, "Soul Blade"},
    {203, "Concentration"},
    {204, "Iron skin"},
    {205, "Aura Barrier"},
    {206, "Panic Cry"},
    {207, "Field of Fear"},
    {208, "Dash"},
    {209, "Fade Step"},
    {210, "Instant Immunity"},
    {211, "Mirage Step"},
    {212, "Resist Barier"},
    {213, "Intuition"},
    {214, "Art of Fierceness"},
    {215, "Intense Blade"},
    {216, "Down Breaker"},
    {217, "Morale Shout"},
    {218, "Fury Shout"},
    {219, "Cat's Recovery"},
    {220, "Bear's Vitality"},
    {221, "Bloody Spirit"},
    {222, "Art of Shout"},
    {223, "Resist intension"},
    {224, "Shadow Shield"},
    {225, "Art of Defense"},
    {226, "Art of Force Control"},
    {227, "Raise Spirit"},
    {228, "Mass Restore"},
    {229, "High Regeneration"},
    {230, "Regeneration"},
    {231, "Weaken"},
    {232, "Hardness"},
    {233, "Energy Field"},
    {234, "Blink"},
    {235, "Spirit Intension"},
    {236, "Force Hardness"},
    {237, "Precision"},
    {238, "Repulsive Armor"},
    {239, "Blind"},
    {240, "Eagle Eye"},
    {241, "Curse of Wither"},
    {242, "Sharpness"},
    {243, "Mana Condense"},
    {244, "Vital Force"},
    {245, "Greater Heal"},
    {246, "Vital Bless"},
    {247, "Mass Heal"},
    {248, "Crushing Blade"},
    {249, "Heal"},
    {250, "Shield Harden"},
    {251, "Mortal Bane"},
    {252, "Enchant"},
    {253, "Earth Guard"},
    {254, "Aqua Vitality"},
    {255, "Wind Movement"},
    {256, "Fire Blade"},
    {257, "Guard Break"},
    {258, "Lightning Blade"},
    {259, "Ice Blade"},
    {261, "Execration"},
    {262, "Hard Luck"},
    {264, "Force Enchanter Dummy Buffing #1"},
    {265, "Force Enchanter Dummy Buffing #2"},
    {266, "Force Enchanter Dummy Buffing #3"},
    {267, "Force Enchanter Dummy Buffing #4"},
    {268, "Art of Curse"},
    {269, "Curse of Freeze"},
    {270, "Field of Enervation"},
    {271, "Field of Execration"},
    {272, "Thrusting Arrow"},
    {273, "Art of Healing"},
    {274, "Art of Sniping"},
    {275, "Attack Ability Enhancement"},
    {276, "Defense Ability Enhancement"},
    {277, "Ice Lord's Will"},
    {278, "Ice Guardian's Blessing"},
    {279, "Wind Agility"},
    {280, "Aqua Restore"},
    {281, "FA Cure"},
    {282, "FA Buff 1"},
    {283, "FS Buff 1"},
    {284, "FS Buff 2"},
    {285, "Boss Battle member buff"},
    {286, "Boss Battle fortress buff"},
    {287, "Magic Control"},
    {288, "Spirit Shield"},
    {289, "Quick Move"},
    {290, "Reflex Shield"},
    {291, "Piercing Spell"},
    {292, "Elemental Enchant"},
    {293, "Enhance Attack"},
    {294, "Enhance Defense"},
    {295, "Enhance Critical"},
    {296, "Enhance Resistance"},
    {297, "Troll's Vigor"},
    {298, "Dragon's Breath"},
    {299, "Focus"},
    {300, "Vitality Mastery"},
    {301, "Mana Mastery"},
    {302, "Offensive Sense"},
    {303, "Defensive Sense"},
    {304, "Force Control"},
    {305, "Reflex"},
    {306, "Sharp Eyes"},
    {307, "Change Force(Magic)"},
    {308, "Change Force(Sword)"},
    {310, "Eyes of Mind"},
    {311, "Sixth Sense"},
    {312, "Ruling Force"},
    {313, "Impact Control"},
    {314, "Damage Absorb"},
    {329, "Astral Enchant"},
    {330, "Astral Gun"},
    {331, "Astral Bow"},
    {332, "Astral Shield"},
    {333, "Earth Aura"},
    {334, "Aqua Aura"},
    {335, "Wind Aura"},
    {336, "Flame Aura"},
    {337, "Ice Aura"},
    {338, "Lightening Aura"},
    {339, "Dummy Skill"},
    {340, "Berserker"},
    {341, "Lancer"},
    {342, "Illusionist"},
    {343, "Grappler"},
    {344, "Chain Caster"},
    {345, "Double Caster"},
    {346, "Multi Shooter"},
    {347, "Twin Gunner"},
    {348, "Counter Attacker"},
    {349, "Shield Master"},
    {350, "Force Enchanter"},
    {351, "Blade Shooter"},
    {352, "Infighter"},
    {353, "Death Scyther"},
    {360, "Board Skill #1"},
    {361, "Board Skill #2"},
    {362, "Board Skill #3"},
    {363, "Board Skill #4"},
    {364, "Bike Charge"},
    {365, "Willie Smash"},
    {366, "Jack Knife Buster"},
    {367, "Drift Slash"},
    {380, "Lancer Attack #1"},
    {381, "Lancer Attack #2"},
    {382, "Lancer Attack #3"},
    {383, "Lancer Attack #4"},
    {384, "Grappler Attack #1"},
    {385, "Grappler Attack #2"},
    {386, "Grappler Attack #3"},
    {387, "Grappler Attack #4"},
    {388, "Shield Master Attack #1"},
    {389, "Shield Master Attack #2"},
    {390, "Shield Master Attack #3"},
    {391, "Twin Gunner Attack #1"},
    {392, "Twin Gunner Attack #2"},
    {393, "Twin Gunner Attack #3"},
    {394, "Twin Gunner Attack #4"},
    {395, "Scyther Attack #1"},
    {396, "Scyther Attack #2"},
    {397, "Scyther Attack #3"},
    {398, "Scyther Attack #4"},
    {399, "Death Scyther Guillotine"},
    {400, "Lance Drive"},
    {401, "Lancer Skill 2"},
    {402, "Crushing Blow"},
    {403, "Grappler Skill 2"},
    {404, "Elemental Festival"},
    {405, "Double Caster Skill 2"},
    {406, "Fatal Shot"},
    {407, "Twin Gunner Skill 2"},
    {408, "Shield Storm"},
    {409, "Shield Master Skill 2"},
    {410, "Prismatic Blade-Cannon"},
    {411, "Blade Shooter Skill 2"},
    {412, "Beam 1"},
    {413, "Beam 2"},
    {414, "Beam 3"},
    {418, "Chance Attack"},
    {419, "Combo Start"},
    {420, "Summon Astral Bike"},
    {421, "Board Chain Attack"},
    {422, "Bike Chain Attack"},
    {423, "Old Bike Skill #3"},
    {424, "Magic Arrow"},
    {425, "Terra Arrow"},
    {426, "Aqua Arrow"},
    {427, "Wind Arrow"},
    {428, "Fire Arrow"},
    {429, "Freezing Arrow"},
    {430, "Lightning Arrow"},
    {431, "Magic Blast"},
    {432, "Stone Blast"},
    {433, "Aqua Blast"},
    {434, "Wind Blast"},
    {435, "Fire Blast"},
    {436, "Ice Blast"},
    {437, "Lightning Blast"},
    {438, "Magic Lance"},
    {439, "Terra Lance"},
    {440, "Aqua Lance"},
    {441, "Wind Lance"},
    {442, "Fire Lance"},
    {443, "Freezing Lance"},
    {444, "Lightning Lance"},
    {445, "Magic Cannon"},
    {446, "Stone Cannon"},
    {447, "Aqua Cannon"},
    {448, "Wind Cannon"},
    {449, "Fire Cannon"},
    {450, "Crystal Cannon"},
    {451, "Lightning Cannon"},
    {452, "Astral Board"},
    {453, "Astral Board Dummy Skill"},
    {454, "Attack UP"},
    {455, "Defense UP"},
    {456, "Resist Critical DMG/Skill AMP UP"},
    {457, "Attack DOWN"},
    {458, "Defense DOWN"},
    {459, "HP Decrease"},
    {460, "GM's Blessing(Lv. 1)"},
    {461, "GM's Blessing(Lv. 2)"},
    {462, "GM's Blessing(Lv. 3)"},
    {463, "Debuff of GM"},
    {464, "Blade Shooter Attack No. 1"},
    {465, "Blade Shooter Attack No. 2"},
    {466, "Blade Shooter Attack No. 3"},
    {467, "Blade Shooter Attack No. 4"},
    {468, "Mighty Wish"},
    {469, "Field of Provocation"},
    {470, "Offensive Bless"},
    {471, "Curse Remove"},
    {472, "Curse Dodge"},
    {473, "Fatality Increase"},
    {474, "Saint's Force"},
    {475, "Axe Destroyer"},
    {476, "Knucklet Striker"},
    {477, "Elemental Dominator"},
    {478, "Launcher Punisher"},
    {479, "Hammer Crusher"},
    {480, "Sword Splitter"},
    {481, "Axe Attack A"},
    {482, "Axe Attack B"},
    {483, "Axe Specialty Level 1"},
    {484, "Axe Specialty Level 2"},
    {485, "Axe Specialty Level 3"},
    {486, "Knucklet Attack A"},
    {487, "Knucklet Attack B"},
    {488, "Knucklet Specialty Level 1"},
    {489, "Knucklet Specialty Level 2"},
    {490, "Knucklet Specialty Level 3"},
    {491, "Elemental Attack A"},
    {492, "Elemental Attack B"},
    {493, "Elemental Specialty Level 1"},
    {494, "Elemental Specialty Level 2"},
    {495, "Elemental Specialty Level 3"},
    {496, "Launcher Attack A"},
    {497, "Launcher Attack B"},
    {498, "Launcher Specialty Level 1"},
    {499, "Launcher Specialty Level 2"},
    {500, "Launcher Specialty Level 3"},
    {501, "Hammer Attack A"},
    {502, "Hammer Attack B"},
    {503, "Hammer Specialty Level 1"},
    {504, "Hammer Specialty Level 2"},
    {505, "Hammer Specialty Level 3"},
    {506, "Split Attack A"},
    {507, "Split Attack B"},
    {508, "Split Specialty Level 1"},
    {509, "Split Specialty Level 2"},
    {510, "Split Specialty Level 3"},
    {511, "2FA exclusive buff"},
    {512, "Ranger"},
    {513, "Heavy Launcher"},
    {514, "Gunner Battle Mode 2 Attack #1"},
    {515, "Gunner Battle Mode 2 Attack #2"},
    {516, "Gunner Battle Mode 2 Attack #3"},
    {517, "Gunner Battle Mode 2 Attack #4"},
    {518, "Surface Impact"},
    {519, "Hit Man"},
    {520, "Hit Man Attack A"},
    {521, "Hit Man Attack B"},
    {522, "Hit Man Speciality Level 1"},
    {523, "Hit Man Speciality Level 2"},
    {524, "Hit Man Speciality Level 3"},
    {525, "Magic Arrow"},
    {526, "Terra Arrow"},
    {527, "Aqua Arrow"},
    {528, "Wind Arrow"},
    {529, "Fire Arrow"},
    {530, "Freezing Arrow"},
    {531, "Lightning Arrow"},
    {532, "Magic Blast"},
    {533, "Stone Blast"},
    {534, "Aqua Blast"},
    {535, "Wind Blast"},
    {536, "Fire Blast"},
    {537, "Ice Blast"},
    {538, "Lightning Blast"},
    {539, "Magic Lance"},
    {540, "Terra Lance"},
    {541, "Aqua Lance"},
    {542, "Wind Lance"},
    {543, "Fire Lance"},
    {544, "Freezing Lance"},
    {545, "Lightning Lance"},
    {546, "Magic Cannon"},
    {547, "Stone Cannon"},
    {548, "Aqua Cannon"},
    {549, "Wind Cannon"},
    {550, "Fire Cannon"},
    {551, "Crystal Cannon"},
    {552, "Lightning Cannon"},
    {553, "Aim Shot"},
    {554, "Targeting Shot"},
    {555, "Slug Shot"},
    {556, "Oppression Shot"},
    {557, "Rolling Launcher"},
    {558, "Force Slug"},
    {559, "Shot Impact"},
    {560, "Living Fog"},
    {561, "Broken Arrow"},
    {562, "Ion Bullet"},
    {563, "Lightning Satellite"},
    {564, "Sunset Missiles"},
    {565, "Grenade Down"},
    {566, "Buster Bombard"},
    {567, "Wide Cover Shot"},
    {568, "Mouse Mk-2"},
    {569, "Call Valkyrie"},
    {570, "Revenger"},
    {571, "Mechanic-crop"},
    {572, "Storm Blitz"},
    {573, "Art of Desperado"},
    {574, "Reactive Technique"},
    {575, "Inspire"},
    {576, "Lock On"},
    {577, "Target Focus"},
    {578, "Sniper Plan"},
    {579, "Castle Rock"},
    {580, "Warfare Matrix"},
    {581, "Platinum Buff (Normal)"},
    {582, "Platinum Buff (Rare)"},
    {583, "Platinum Buff (Unique)"},
    {584, "Platinum Buff (Master)"},
    {585, "Platinum Buff (Epic)"},
    {586, "Platinum Buff (Legend)"},
    {587, "GM's Blessing (Lv.4)"},
    {588, "Wing Fly"},
    {589, "Wing Assault"},
    {590, "Wing Protect"},
    {591, "Force Field"},
    {592, "Legend Arena buff"},
    {593, "Bless of Unity"},
    {594, "Explorer's Blessing (Lv.1)"},
    {595, "Explorer's Blessing (Lv.2)"},
    {596, "Explorer's Blessing (Lv.3)"},
    {597, "Saint's Force of Warrier"},
    {598, "Saint's Force of Blader"},
    {599, "Saint's Force of Wizzard"},
    {600, "Saint's Force of Force Archer"},
    {601, "Saint's Force of Force Shielder"},
    {602, "Saint's Force of Force Blader"},
    {603, "Saint's Force of Gladiator"},
    {604, "Saint's Force of Force Gunner"},
    {605, "Frenzy (Target Focus)"},
    {606, "Frenzy"},
    {607, "Dooms Blade"},
    {608, "Force Unleashing (Target Focus)"},
    {609, "Force Unleashing"},
    {610, "Sharp Instinct"},
    {611, "Preemptive Defense"},
    {612, "Elemental Discharge"},
    {613, "Furious"},
    {614, "Overfire"},
    {615, "Rhinos Toughness"},
    {616, "Vampiric Movement"},
    {617, "Force Shell"},
    {618, "Sprit Walk"},
    {619, "Shield Castle"},
    {620, "Elemental Barrier"},
    {621, "Unbreakable"},
    {622, "Tactical Armor"},
    {623, "Charging Spirit"},
    {624, "Blind Anger"},
    {625, "Warrior Mastery"},
    {626, "Blader Mastery"},
    {627, "Wizard Mastery"},
    {628, "Force Archer Mastery"},
    {629, "Force Shielder Mastery"},
    {630, "Force Blader Mastery"},
    {631, "Gladiator Mastery"},
    {632, "Force Gunner Mastery"},
    {633, "Skull Shooter"},
    {634, "Bone Javelin"},
    {635, "Dark Ray"},
    {636, "Dark Explosion"},
    {637, "Death Crasher"},
    {638, "Bone Ballista"},
    {639, "Dark Ray Diffusion"},
    {640, "Night Fall"},
    {641, "Shadow Fall"},
    {642, "Dark Scream"},
    {643, "Bone Gluttony"},
    {644, "Deadly Smasher"},
    {645, "Assassinate Bomber"},
    {646, "Venom's Affair"},
    {647, "Demons Waltz"},
    {648, "Creeping Pain"},
    {649, "Revenge of Nature"},
    {650, "Spirit Swarm"},
    {651, "Soul intake"},
    {652, "Totem of Venom"},
    {653, "Butcher's Hell"},
    {654, "Totem of Dystrophy"},
    {655, "Offering of Hell"},
    {656, "Darkmatter Fallen"},
    {657, "Totem of Absorption"},
    {658, "Harvest of Reaper"},
    {659, "Spirit Redemption"},
    {660, "Vanquish of Evil"},
    {661, "Corps Explosion"},
    {662, "Hell's Requiem"},
    {663, "Warlock"},
    {664, "Grimoire"},
    {665, "Grimoire Attack #1"},
    {666, "Grimoire Attack #2"},
    {667, "Demolition Ray"},
    {668, "Demon Trigger"},
    {669, "Demon Trigger Attack A"},
    {670, "Demon Trigger Attack B"},
    {671, "Demon Trigger Speciality Stage 1"},
    {672, "Demon Trigger Speciality Stage 2"},
    {673, "Demon Trigger Speciality Stage 3"},
    {674, "Saint's Force of Dark Mage"},
    {675, "Defensive Posture"},
    {676, "Crumble Body"},
    {677, "Curse of Bleeding"},
    {678, "Leg Fracture"},
    {679, "Bloodless"},
    {680, "Skin Weakness"},
    {681, "Silence"},
    {682, "Bone Shield"},
    {683, "Petrified One"},
    {684, "Art of Blood Thrust"},
    {685, "Calamity Soul"},
    {686, "Bloody Bless"},
    {687, "Dark Mage Mastery"},
    {688, "Vital Recovery"},
    {689, "Adaptive Barrier"},
    {690, "Circle Crafting"},
    {691, "Amplify"},
    {692, "Force Overload"},
    {693, "GM's Blessing (Lv.5)"},
    {694, "Sanctuary Conqueror"},
    {695, "Weapon Refinement"},
    {696, "Massive Thrust"},
    {697, "Poison Mist Ray"},
    {698, "Descent : Retribution"},
    {699, "Surging Will"},
    {700, "Assert Signum"},
    {701, "Cube Seeker (Lv.1)"},
    {702, "Cube Seeker (Lv.2)"},
    {703, "Cube Seeker (Lv.3)"},
    {704, "Clue in the Abyss"},
    {705, "Dazzling Growth"},
    {706, "Exploration of Abyss"},
    {707, "Journey of Experience"},
    {708, "New growth"},
    {709, "Gentle Warmth"},
    {710, "Brilliant Flame (Red)"},
    {711, "Brilliant Flame (Blue)"},
    {712, "Brilliant Flame (Green)"},
    {713, "Brilliant Flame (Violet)"},
    {714, "Brilliant Flame"},
    {715, "Starfall"},
};

const char *
pw_skill_name(uint32_t id)
{
    unsigned lo = 0;
    unsigned hi = (unsigned)(sizeof(k_names) / sizeof(k_names[0]));
    while (lo < hi) {
        unsigned mid = lo + (hi - lo) / 2u;
        if (k_names[mid].id == id) {
            return k_names[mid].name;
        }
        if (k_names[mid].id < id) {
            lo = mid + 1u;
        } else {
            hi = mid;
        }
    }
    return NULL;
}
